<?php

use App\Link;
use Illuminate\Database\Seeder;

class SeedLinksTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $from = date("Y");
        $to = $from + 1;
        \DB::table('links')->truncate();

        $links = [
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/board-of-trustees.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/administration.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/faculty.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/accreditations.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/about-us/disclaimer-statement.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/calendar/index.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/calendar/fall-weekend.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/calendar/spring-full.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/calendar/spring-weekend.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/calendar/pharmacy.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/index.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/transfer-credit.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/independent.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/tutorial.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/institutional-review-board.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/education-records.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/integrity.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/appeals.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/policies/petition.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/index.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/requirements.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/awards.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/standards.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/standing-probation-dismissal.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/support.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/registration.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-information/transcripts.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/about-graduate-education.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/application.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/conduct.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/deferral-readmission.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/international.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/designations.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/catalog-degree-requirements.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/program-change.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/enrollment.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/admissions/immunization.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/financial/', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/financial/payment.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/financial/refund.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/financial/aid.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/career-center.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/college-store.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/dining.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/disability.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/childcare.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/wellness.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/library.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/math.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/oit.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/print.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/safety.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/writing.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/resources/services-facilities/veterans.dot', 'graduate'],
			['http://catalog.sjfc.edu/graduate/2015-2016/academic-programs/academic-programs.dot', 'graduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/history.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/creed.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/accreditations.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/board-of-trustees.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/administration.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/faculty.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/about-us/disclaimer-statement.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/calendar/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/calendar/fall-weekend.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/calendar/spring-full.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/calendar/spring-weekend.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/integrity.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/index.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/catalog.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/major.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/minor.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/electives.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/liberal-arts.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/dual-degrees.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/requirements/after-degree.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/core/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/core/transfer.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/independent.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/tutorial.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/topic.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/examination.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/experiential.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/petition.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/transfer-credit.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/attendance.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/nonmatriculated.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/courses/programs.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/grading/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/grading/academic-progress.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/registration.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/honors/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/honors/academic-awards.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/regulations/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/regulations/academic-appeals.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/regulations/graduation-rates.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/regulations/research.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-information/transcripts.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/academic-affairs.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/career-center.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/labs.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/library.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/math.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/media.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/nursing.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/oit.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/veterans.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/academic-support/writing.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/visits.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/highschool.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/immunization.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/transfer.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/conduct.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/international.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/amnesty.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/sophomore.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/servicemembers.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/heop.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/cbe.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/admissions/summer.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/payment.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/refund.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/aid.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/standards.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/nys-grants.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/federal-grants.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/college-private-scholarships-grants.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/loans.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/financial/other-assistance.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/athletics.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/campus-life.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/campus-ministry.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/wellness.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/diversity.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/residential-life.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/safety.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/services.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/student-life/student-affairs.dot', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/resources/civic-engagement/', 'undergraduate'],
			['http://catalog.sjfc.edu/undergraduate/2015-2016/academic-programs/academic-programs.dot', 'undergraduate'],
        ];

        foreach ($links as $key => $link) {

            $l = new Link;

            $l->url  = $link[0];
            $l->type = $link[1];
            $l->year = "$from - $to";

            $l->save();
        }
    }
}
